service: final

custom:
  bucket: takehome94

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
    
functions:
  addSongs:
    handler: addSongs.addSongs
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
  
  remove:
    handler: remove.remove
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectRemoved:*
  
  get:
    handler: final/get.get
    events:
      - http:
          path: final/{id}
          method: get
          cors: true
  
  list:
    handler: final/list.list
    events:
      - http:
          path: final
          method: get
          cors: true
  
  create:
    handler: final/create.create
    events:
      - http:
          path: final
          method: post
          cors: true
          



resources:
  Resources:
    Exam:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Exam
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Exam5:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Exam5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1