service: finalexam

custom:
  bucket: takehome931

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
    
functions:
  addFile:
    handler: addFile.addFile
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
  
  deleteFile:
    handler: deleteFile.deleteFile
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectRemoved:*
  
  searchSong:
    handler: final/searchSong.searchSong
    events:
      - http:
          path: final/{name}
          method: get
          cors: true
  
  songList:
    handler: final/songList.songList
    events:
      - http:
          path: final
          method: get
          cors: true
  
  playlist:
    handler: final/playlist.playlist
    events:
      - http:
          path: final
          method: post
          cors: true



resources:
  Resources:
    Exam93:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Exam93
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Exam95:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Exam95
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1